version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring
    container_name: spring-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    container_name: spring-redis
    restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    environment:
      - REDIS_ARGS=--requirepass root